### ISSUE TITLE
Exception: Missing command method: saveConnectionsToFile

### ISSUE THREAD

**Issue by Felix-Tr** [Zbysekz/HTMpandaVis#8]
Hi all,
First of thanks for the contribution of pandaVis, I would like to use the visualizations of the _l2l4l6a experiment_ for a study project.

When running _experiment1.py_  of the [2d object modelling project](https://github.com/htm-community/htm-2d-object-modeling) with the setting `self.bakePandaData = True` ([line 72](https://github.com/Zbysekz/htm-2d-object-modeling/blob/82f2485cc1e617a13a3fec3f4b64afeadd89136d/python/experiment1.py#L72)), I get the error 
`Exception: Missing command method: saveConnectionsToFile`

<details>
  <summary>full traceback</summary>

```
Traceback (most recent call last):
  File "/home/felix/labcourse2022/htm-2d-object-modeling/python/experiment1.py", line 380, in <module>
    experiment.learn(parameters, 0)
  File "/home/felix/labcourse2022/htm-2d-object-modeling/python/experiment1.py", line 270, in learn
    self.network.learn(streamForAllColumns)
  File "/home/felix/labcourse2022/htm-2d-object-modeling/venv/lib/python3.8/site-packages/htm.core-2.1.16-py3.8-linux-x86_64.egg/htm/advanced/support/logging_decorator.py", line 84, in _fn
    return fn(instance, *args, **kwargs)
  File "/home/felix/labcourse2022/htm-2d-object-modeling/python/l2l4l6Framework/l2_l4_l6_Network.py", line 157, in learn
    self.sendReset()
  File "/home/felix/labcourse2022/htm-2d-object-modeling/venv/lib/python3.8/site-packages/htm.core-2.1.16-py3.8-linux-x86_64.egg/htm/advanced/support/logging_decorator.py", line 84, in _fn
    return fn(instance, *args, **kwargs)
  File "/home/felix/labcourse2022/htm-2d-object-modeling/python/l2l4l6Framework/l2_l4_l6_Network.py", line 132, in sendReset
    self.network.run(1)
  File "/home/felix/labcourse2022/htm-2d-object-modeling/venv/lib/python3.8/site-packages/HTMpandaVis-0.1-py3.8.egg/pandaBaker/pandaNetwork.py", line 37, in run
  File "/home/felix/labcourse2022/htm-2d-object-modeling/venv/lib/python3.8/site-packages/HTMpandaVis-0.1-py3.8.egg/pandaBaker/pandaBaker.py", line 96, in StoreIteration
  File "/home/felix/labcourse2022/htm-2d-object-modeling/venv/lib/python3.8/site-packages/htm.core-2.1.16-py3.8-linux-x86_64.egg/htm/bindings/regions/PyRegion.py", line 354, in executeMethod
    raise Exception('Missing command method: ' + methodName)
Exception: Missing command method: saveConnectionsToFile
```

</details>

in the current htm.core repository the region _py.GridCellLocationRegion_ doesn't implement the _saveConnectionsToFile_ Method (executed [here](https://github.com/htm-community/HTMpandaVis/blob/44501ae535db27ff3e0bd8fb0718c5ca07c3f68a/pandaBaker/pandaBaker.py#L95)).

I assume implementing the method and saving the right connections will fix this problem and I will try changing the code in these classes to implement the method.
But as I'm not super familiar with all the htm.core bindings & stuff yet I was wondering if there is a workaround for that you (@Zbysekz) used for the visualization in your [video](https://www.youtube.com/watch?v=vBUx-75t11U)

Best,
Felix

**Comment by Felix-Tr** [comment]
**Update**:
I get the visualization now by adding the method in _py.GridCellLocationRegion_ just with a pass
```
    def saveConnectionsToFile(self, filepath):
        """
        Binary dumps connections objects into file specified, adding suffix specifying the type
        """
        pass
```

or removing it from the iteration [here](https://github.com/htm-community/HTMpandaVis/blob/44501ae535db27ff3e0bd8fb0718c5ca07c3f68a/pandaBaker/pandaBaker.py#L95).

After rebuilding htm.core / pandaBaker it seems to work for know as cell activity, distal / apical connections are present in the pandavis visualization.

**Comment by Zbysekz** [comment]
@Felix-Tr I am glad that there is some interest or continuation in this project.
This way you don't bake connections for gridcell location region - you should execute this:
```    
def saveConnectionsToFile(self, filepath):
        """
        Binary dumps connections objects into file specified, adding suffix specifying the type
        """
        i = 0
        for m in self._modules:
            with open(filepath+"_"+str(i)+".dump", "wb") as f:
                f.write(m.connections.save())
            i+=1
```
I did quick search and actually, my last commit(ccc275ae97e2f43345390b17fa8b0d90d3d908b3) to the htm.core repository is adding just that - to the branch "dev_gridLocationlayer". But you couldn't know that, i probably haven't started pull-request there, sorry.

**Comment by Felix-Tr** [comment]
Thank you very much for the quick reply :) I didn't find the branch you mention in the htm.core repo but the method was enough to run it succesfully including visualizing the basal connections from L6a to L4. I will close the issue for now as it's related to htm.core. Depending on wheater you want to make the pull request I could also do that at the end of my study project, as well as regarding other problems I may encounter using pandaBaker.

**Comment by Zbysekz** [comment]
> I could also do that at the end of my study project, as well as regarding other problems I may encounter using pandaBaker.

That would be nice, feel free to contribute to the project.
Have a good day
